manifest:
  remotes:
    - name: madswolf
      url-base: https://github.com/madswolf
    - name: petejohanson
      url-base: https://github.com/petejohanson

  projects:
    - name: zmk
      remote: petejohanson
      revision: core/move-to-zephyr-4-1
      import: app/west.yml

    # Module for PS/2 mouse & TP driver
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: madswolf
      revision: main

  self:
    path: config
    
